### ISSUE TITLE
Same Bug on macOS Big Sur

### ISSUE THREAD

**Issue by lavalse** [nodes-io/nodes-io#15]
### Describe the bug
I can't create or open a new project in my macbook

### To Reproduce
1. Go to 'Dashboard'
2. Click on 'OPEN FOLDER'
3. Open the project I just created
4. wilt a long time , seeing loading icom
5. nothing , just a blank window

### Expected behavior
I think it should open the interface.

### Environment Information:
- app: 1.0.0-beta.1
- os: macOS Big Sur 11.1

**Comment by vorg** [comment]
Hi @lavalse could you try downloading previous beta as described here https://github.com/nodes-io/nodes-io/issues/14#issuecomment-753660059 ?

**Comment by dmnsgn** [comment]
Hi @lavalse ,

We've just published a new version of Nodes: https://github.com/nodes-io/nodes-io/releases/download/v1.0.0-beta.2/Nodes-1.0.0-beta.2.dmg

If you still experience this issue, do let us know on here: https://github.com/nodes-io/nodes-io/issues/14
