### ISSUE TITLE
Notarize application to avoid verification warning

### ISSUE THREAD

**Issue by Outcue** [nodes-io/nodes-io#4]
### Describe the bug
Launching Nodes on MacOs Catalina show an error. It is possible to circumvent this dialog by using the context menu, opening the app and then allowing Nodes to launch, but it would be preferable to provide a notarized application.

### To Reproduce
Double-click download app

### Expected behavior
The application should launch

### Screenshots
<img width="429" alt="bug" src="https://user-images.githubusercontent.com/65915337/99417647-61363200-28b7-11eb-8f5c-324950523fbe.png">

### Environment Information (please complete the following information):
MacOs Catalina

**Comment by vorg** [comment]
Hi @Outcue, we are working on that. In the meantime the solution is indeed to right click on the Nodes.app, choose `Open` 

![Screenshot 2020-11-20 at 11 49 35](https://user-images.githubusercontent.com/171001/99797224-be83ea80-2b26-11eb-9e16-948abb448c12.jpg)

and then new option `Open` will appear allowing to actually open the app. You should need to do it only once.

![Screenshot 2020-11-20 at 11 49 49](https://user-images.githubusercontent.com/171001/99797153-9eecc200-2b26-11eb-8975-926ed5519241.jpg)

**Comment by vorg** [comment]
Explanation from Apple https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

**Comment by dmnsgn** [comment]
Fixed in 1.0.0-beta.1
