### ISSUE TITLE
Bug Report: Mistakes in Tutorial text

### ISSUE THREAD

**Issue by anselanza** [nodes-io/nodes-io#7]
### Describe the bug
Spelling mistakes/typos in Tutorial text

### To Reproduce
Read tutorial

#### 03: Create a graphic canvas

> Click on the node in the Graph Editor and change **it's** name

should be

> change **its** name

...

> other graphs and project 

should be

> other graphs and project**s**

#### 04: Add a grid
> Create another Custom node and rename it to Drag Grid.

should be

> Create another Custom node and rename it to Dra**w** Grid.

(this is confusing because otherwise you might think that there is supposed to be some dragging interactivity or something!)

...

Further down, the same mistake is made again:

> drag a connection to the in port of Drag Grid canvas.

should be

> drag a connection to the in port of Dra**w** Grid canvas.

...

> Let’s make it breath a bit 

should be (breath = noun, breathe = verb)

> Let's make it **breathe** a bit

#### 09. Extra: add more shapes
There is no text instruction to connect the `Small Circle` node into the graph, although there is an illustration for this.

**Comment by dmnsgn** [comment]
All fixed! Thank you for all the suggestions.
